# helm -n monitoring install grafana grafana/grafana -f grafana.values.yaml
---
admin:
  existingSecret: grafana-admin-credentials
  userKey: username
  passwordKey: password
dashboards:
  default:
    cert-manager:
      gnetId: 11001
      datasource: Prometheus
    flux-cluster-reconciliation:
      url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
    flux-control-plane:
      url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
    kuberentes-deployments:
      gnetId: 8588
      datasource: Prometheus
    node-exporter:
      gnetId: 11074
      datasource: Prometheus
    temperature-humidity:
      url: https://raw.githubusercontent.com/aledegano/homelab/main/dashboards/temp-humid.json
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        isDefault: true
grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: "Main Org."
    org_role: "Viewer"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  hosts:
    - grafana.adegano.homelabs.eu
  tls:
    - hosts:
        - grafana.adegano.homelabs.eu
      secretName: grafana-tls
nodeSelector:
  kubernetes.io/hostname: raspi3
resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 300m
    memory: 256Mi
