# helm -n domotics install mosquitto k8s-at-home/mosquitto -f mosquitto.values.yaml
---
service:
  main:
    type: NodePort
    ports:
      http:
        enabled: false
      mqtt:
        enabled: true
        port: 1883
        nodePort: 31883
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi
