apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090

    - job_name: node
      scrape_interval: 15s
      static_configs:
        - targets: ['node-exporter:9100']

    - job_name: sensor
      scrape_interval: 15s
      static_configs:
        - targets: ['telegraf:9090']

    - job_name: flux
      scrape_interval: 15s
      static_configs:
        - targets: ['flux-metrics.flux.svc.cluster.local:3031']
