apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090

    - job_name: 'node'
      scrape_interval: 5s
      static_configs:
        - targets: ['node-exporter:9100']
