---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cert-manager.yaml
  - k8s-at-home.yaml
  - grafana.yaml
  - influxdata.yaml
  - prometheus.yaml
