---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: metrics
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "13.8.0"
  interval: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: metrics
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "6.8.4"
  interval: 5m
  values:
    admin:
      existingSecret: grafana-admin-credentials
      userKey: username
      passwordKey: password
    dashboards:
      default:
        node-exporter:
          gnetId: 11074
          datasource: Prometheus
        kuberentes-deployments:
          gnetId: 8588
          datasource: Prometheus
    dashboardProviders:
     dashboardproviders.yaml:
       apiVersion: 1
       providers:
       - name: 'default'
         orgId: 1
         folder: ''
         type: file
         disableDeletion: false
         editable: true
         options:
           path: /var/lib/grafana/dashboards/default
    datasources:
     datasources.yaml:
       apiVersion: 1
       datasources:
       - name: Prometheus
         type: prometheus
         url: http://prometheus-server
         isDefault: true
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_name: "Main Org."
        org_role: "Viewer"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/redirect-entry-point: https
      hosts:
      - grafana.adegano.homelabs.eu
      tls:
      - hosts:
        - grafana.adegano.homelabs.eu
        secretName: grafana-tls
