apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  labels:
    app: minio
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 30900
    protocol: TCP
  selector:
    app: minio
