---
# Source: telegraf/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  labels:
    app.kubernetes.io/name: telegraf
    helm.sh/chart: telegraf-1.2.0
    app.kubernetes.io/managed-by: Helm
data:
  telegraf.conf: |+

    [agent]
      collection_jitter = "0s"
      debug = false
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true
    [[processors.enum]]
      [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2

    [[outputs.prometheus_client]]
      listen = ":9090"

    [[inputs.mqtt_consumer]]
      servers = ["tcp://192.168.1.116:31883"]
      topics = [
        "/sensor/#",
      ]
      data_format = "value"