---
# Source: telegraf/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app.kubernetes.io/name: telegraf
    helm.sh/chart: telegraf-1.2.0
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: "TCP"
    name: "prometheus-scrape"
  selector:
    app.kubernetes.io/name: telegraf
