---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.16.12
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 9001
        - containerPort: 1883
