apiVersion: v1
kind: Service
metadata:
  name: mosquitto-svc
  labels:
    app: mosquitto
spec:
  type: NodePort
  ports:
  - name: mosquitto-default-listener
    port: 1889
    nodePort: 31883
    protocol: TCP
  - name: mosquitto-extra-listener
    port: 9001
    nodePort: 30901
    protocol: TCP
  selector:
    app: mosquitto
