---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
  namespace: flux-system
data:
  defaults: |
    grafana:
      ingress:
        hosts:
          - grafana-new.raspi.hal
    prometheus:
      prometheusSpec:
        storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-storage
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '12.2.4'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      valuesKey: defaults
      name: kube-prometheus-stack-values
    - kind: Secret
      name: grafana-admin-credentials
      valuesKey: password
      targetPath: grafana.adminPassword
