apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: ClusterIP
  ports:
  - name: grafana-web
    port: 3000
    protocol: TCP
  selector:
    app: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-node
spec:
  type: NodePort
  ports:
  - name: grafana-web-node
    port: 3000
    nodePort: 30300
    protocol: TCP
  selector:
    app: grafana
