- name: Deploy k3s
  hosts: all

  roles:
    - role: xanmanning.k3s
      k3s_release_version: v1.19.4+k3s1
      k3s_become_for_all: yes
      become: yes

  tasks:
  - name: Setup | remove pi user
    become: yes
    user:
      name: "pi"
      state: absent

  - name: local-storage
    become: yes
    file:
      path: /data
      state: directory

- name: get kubectl config
  hosts: master
  tasks:
  - name: Ensure dest dir for kubectl conf exists
    local_action:
      module: file
      path: ~/.kube/
      state: directory

  - name: Get k3s.conf
    become: yes
    fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: ~/.kube/config
      flat: yes

  - name: Update host name in k3s config
    local_action:
      module: replace
      path: ~/.kube/config
      regexp: '127.0.0.1'
      replace: "{{ ansible_host }}"

  - name: Ensure remote dir for kubectl conf exists
    file:
      path: "/home/{{ ansible_user_id }}/.kube"
      state: directory

  - name: Copy k3s config in raspi user home
    become: yes
    copy:
      remote_src: True
      src: /etc/rancher/k3s/k3s.yaml
      dest: "/home/{{ ansible_user_id }}/.kube/config"
      owner: "{{ ansible_user_id }}"
