---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app: web-server
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: web-server
    port: 80
    protocol: TCP
  selector:
    app: web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
        tier: frontend
    spec:
      containers:
      - image: nginx:1.19.4
        name: web-server
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-server
spec:
  rules:
  - host: adegano.homelabs.eu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-server
            port:
              name: web-server
